name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send email
        uses: danieltrut/send-mail@v1.0.2
        with:
          host: smtp.google.com
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: danieltrut
          from: ${{secrets.MAIL_WORKFLOW}}
          subject: Github Actions job result
          body: file://README.md
          attachments: '[{"path":"README.md"}]'
          to: brain11265@gmail.com